
train_data_path: /content/drive/MyDrive/ICON-hindi-GEN/train_hin.csv   #path to the training dataset
val_data_path: /content/drive/MyDrive/ICON-hindi-GEN/train_hin.csv       #path to the validation dataset
test_data_path: /content/drive/MyDrive/ICON-hindi-GEN/test_hin.csv    #path to the test dataset
train_text: Text                                   #name of the column containing text in train dataset
train_label: GENENC                                  #name of the column containing label in train dataset
val_text: Text                                     #name of the column containing text in val dataset
val_label: GENENC                                    #name of the column containing label in val dataset
test_text: Text                                    #name of the column containing text in test dataset
test_label: GENENC                                   #name of the column containing label in test dataset
save_model_path: final.bin                     #path to save model
finetuned_model_path: final.bin                #path to the finetuned model
save_metrics_path: metrics.json                     #path to save the metics file
save_preds_path: preds.csv                          #path to save the predictions